import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Simply Scribbled",
//   description: "Generated by Gopika ",
// };

export const metadata = {
  title: "Simply Scribbled",
  description: "Generated by Gopika",
  themeColor: "#e60023",
  icons: {
    icon: "/icons/icon-192x192.png",  // Favicon & PWA icon
    apple: "/icons/icon-512x512.png", // Apple Touch Icon
  },
  manifest: "/manifest.json",  // Link to PWA Manifest
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

